command:
  - "streamlit"
  - "run"
  - "app.py"

env:
  - name: "DATABRICKS_HOST"
    value: "fevm-serverless-stable-awn-fts.cloud.databricks.com"
  - name: "DATABRICKS_SQL_WAREHOUSE_HTTP_PATH"
    value: "/sql/1.0/warehouses/YOUR_WAREHOUSE_ID_HERE"
  - name: "DATABRICKS_TOKEN"
    valueFrom: "token"
